DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS books;

CREATE TABLE roles(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255));
CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255), password VARCHAR(255));
CREATE TABLE users_roles(user_id INT, role_id INT);

CREATE TABLE books(id INT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(255), author VARCHAR(255), quantity INT);

INSERT INTO roles (id, name) VALUES (1, 'ADMIN');
INSERT INTO roles (id, name) VALUES (2, 'USER');
